name: Vue CI

on:
  pull_request:
    paths: ['web/**']
  push:
    branches: [main]
    paths: ['web/**']

jobs:
  test:
    uses: yarkivaev/npm-workflows/.github/workflows/test.yml@main
    with:
      node-version: '22'
      working-directory: web
