name: Vue CI

on:
  pull_request:
    paths: ['web/**']
  push:
    branches: [main]
    paths: ['web/**']

jobs:
  ci:
    uses: yarkivaev/npm-workflows/.github/workflows/ci.yml@main
    with:
      node-version: '22'
      lint: false
      working-directory: web
